GRANT USAGE ON SCHEMA EXPERIMENTS TO masmpd_user;

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA EXPERIMENTS TO masmpd_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA EXPERIMENTS
GRANT SELECT, INSERT, UPDATE ON TABLES TO masmpd_user;